name: demo1

defaults:
  run:
    shell:
      # as login shell for conda envs
      bash -l {0}

env:
  PACKAGE_NAME: ghactions_demo
  SPHINX_DOCS_PATH: $HOME/docs
  SPHIX_DOCS_HTML: $HOME/docs/build/html
  CONDA_BLD_DIR: /tmp/bld_dir
  CONDA_LABEL: "cid-test"

on:
  # all pushes except vM.N.P tagged stable release
  push:
    branches: ["*"]
    tags-ignore: ["v.[0-9].[0-9].[0-9]"]

  pull_request:

  release:
    types: [published]
    branch: main

jobs:
  ci:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        pyver: ["3.6", "3.7", "3.8"]
    env:
      PY_VER: ${{ matrix.pyver }}

    # outputs:
    #   deploy-type: ${{ steps.conda-build.outputs.deploy-type }}
    #   tarball: ${{ steps.conda-build.outputs.tarball }}

    steps:
      - uses: actions/checkout@v2

      - name: install
        run: echo "installing $PY_VER"

      - name: build conda pkg
        id: conda-build
        run: |
          echo "building conda pkg $PY_VER"
          tarball=0.0.0.dev0
          if [[ $tarball =~ ^([0-9]+\.){3}\.dev[0-9]+$ ]]; then CONDA_LABEL="pre-release"; fi
          if [[ $tarball =~ ^([0-9]+\.){2}\.[0-9]+ ]]; then CONDA_LABEL="pre-release"; fi
          echo "CONDA_LABEL=$CONDA_LABEL" >> $GITHUB_ENV
          echo "TARBALL=$tarball" >> $GITHUB_ENV

      - name: pytest
        run: echo pytesting $PY_VER $CONDA_LABEL for TARBALL=$TARBALL

      - name: deploy conda pkg
        run: echo conda upload $PY_VER $CONDA_LABEL for TARBALL=$TARBALL

      - name: build sphinx docs
        run: echo building sphinx docs $PY_VER $CONDA_LABEL for TARBALL=$TARBALL

      - name: deploy sphinx docs
        run: echo ghpages upload $PY_VER $CONDA_LABEL for TARBALL=$TARBALL

      - name: build sdist
        run: echo building sdist $PY_VER $CONDA_LABEL for TARBALL=$TARBALL

      - name: deploy test.pypi
        run: echo uploading sdist to TEST.pypi.org $PY_VER $CONDA_LABEL for TARBALL=$TARBALL

      - name: deploy pypi
        run: echo uploading sdist to PYPI.org $PY_VER $CONDA_LABEL for TARBALL=$TARBALL
