name: test_checkout
env:
  PKG_NAME: ghactions_demo
on: push

jobs:
  checkout:
    runs-on: [ubuntu-latest]
    steps:
      - name: dump event
        run: |
          git clone ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/${GITHUB_SHA} .
          cd $PKG_NAME


