name: test_checkout
env:
  PKG_NAME: ghactions_demo

on:
  push:
    branches: ["*"]
    tags-ignore:
      - v[0-9].[0-9].[0-9]  # prevent double runs on tagged release

  pull_request:

  release:
    types: [published]

jobs:
  checkout:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    matrix:
      py_ver: [3.6, 3.7]
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - run: |
          ls -lR
          git config -l

      - name: dump event payload
        run: cat $GITHUB_EVENT_PATH

      # - name: init commit push test 
      #   run: |
      #     # echo "actions git config global"
      #     # git config -l

      #     mkdir -p $HOME/tmp_docs
      #     cd $HOME/tmp_docs
      #     echo "stub file" >> stub.txt
      #     ls -l

      #     git init
      #     # git remote add origin ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
      #     user_name="docs_${GITHUB_EVENT_NAME}_bot"
      #     git config user.email "${user_name}@the.cloud.org"
      #     git config user.name "$user_name"
      #     git config -l
      #     git checkout --orphan test_gh-pages
      #     git add -A
      #     git ls-files
      #     git commit -a -m "spudtr CID workflow docs update"
      #     # this works w/ personal token and secret 
      #     # git remote add origin "https://turbach:${GH_ACTION_PUSH}@github.com/turbach/ghactions_demo"
      #     # git remote add origin "https://turbach:${GH_TOKEN}@github.com/turbach/ghactions_demo"
      #     # git remote add origin "https://turbach:${{ secrets.github_token }}@github.com/turbach/ghactions_demo"
      #     # GITHUB_TOKEN is not automatically accessible in run shells
      #     git remote add origin "https://${user_name}:${{ secrets.github_token }}@github.com/${GITHUB_REPOSITORY}"
      #     git push -u origin test_gh-pages --force

  
