name: test_checkout
on: push

jobs:
  checkout:
    runs-on: [ubuntu-latest]
    steps:
      - name: dump event
        run: |
          echo ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/${GITHUB_SHA}

