name: test_checkout
env:
  PKG_NAME: ghactions_demo
on: push

jobs:
  checkout:
    runs-on: [ubuntu-latest]
    steps:
      - name: dump event
        run: |
          mkdir -p ${GITHUB_REPOSITORY}
          cd ${GITHUB_REPOSITORY}
          git init
          git remote add origin ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
          git fetch origin ${GITHUB_SHA}
          git reset --hard FETCH_HEAD
          git branch
          git status
          ls -R


