# composite run steps 
name: conda-build

defaults:
  run:
    shell:
      bash -l {0}

runs:
  using: "composite"
  steps:
    - name: this might build a conda package
      run: echo "this is a test"
